In [1]:
class Bill:
    item={"HDD":5000,"RAM":2000,"Printer":6000,"Pendrive":800}
class cashpayment(Bill):
    def __init__(self,total):
        print("Method Payment is cash")
        print("Total amount to pay :",total)
        n20=int(total/2000)
        total=total%2000
        n5=int(total/500)
        total=total%500
        n2=int(total/200)
        total=total%200
        n1=int(total/100)
        total=total%100
        print("")
        print("2000 Rs Notes::",n20)
        print("500 Rs Notes::",n5)
        print("200 Rs Notes::",n2)
        print("100 Rs Notes::",n1)
class chequepayment(Bill):
    def __init__(self,total):
        print("Method Payment is cheque")
        print("Total amount to pay :",total)
        print("enter cheque number:")
        chno=input("enter here")
        print("enter bank  name:")
        bkno=input("enter here")
        print("cheque number:",chno)
        print("bank name:",bkno)
s=Bill()
total=0
for i in  s.item.keys():
    print(i,s.item[i])
    print("-----------")
    print("Want this item ?  (Y/N)",end="")
    ans=input("")
    if(ans.lower()=="y"):
        print("enter no of ",i)
        qu=int(input(""))
        total=total+qu*(int(s.item[i]))
print("1. Cash Payment")
print("2. Cheque Payment")
n=int(input("enter here"))
if(n==1):
    cash=cashpayment(total)
elif n==2:
    chk=chequepayment(total)
else:
    raise Exception("enter from 1 or 2")

HDD 5000
-----------
Want this item ?  (Y/N)y
enter no of  HDD
1
RAM 2000
-----------
Want this item ?  (Y/N)y
enter no of  RAM
1
Printer 6000
-----------
Want this item ?  (Y/N)y
enter no of  Printer
1
Pendrive 800
-----------
Want this item ?  (Y/N)y
enter no of  Pendrive
1
1. Cash Payment
2. Cheque Payment
enter here1
Method Payment is cash
Total amount to pay : 13800

2000 Rs Notes:: 6
500 Rs Notes:: 3
200 Rs Notes:: 1
100 Rs Notes:: 1


## Numpy

In [2]:
import numpy as np
import sys
s=range(1000)
print("size of each element of lis in bytes:",sys.getsizeof(s))
print("size of whole list in bytes:",sys.getsizeof(s)*len(s))


size of each element of lis in bytes: 48
size of whole list in bytes: 48000


In [3]:
d=np.arange(1000)
print("Size of each elemnt of numpy array in bytes",d.itemsize)
print("size of whole numpy array in bytes:",d.itemsize*d.size)

Size of each elemnt of numpy array in bytes 4
size of whole numpy array in bytes: 4000


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [7]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[:1,:3])

[[1 2 3]]


In [8]:
print(arr[:1])

[[1 2 3 4 5]]


In [9]:
arr.shape

(2, 5)

In [10]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=3)
print(arr)

[[[1 2 3 4 5]]]
