In [1]:
class Bill:
    item={"HDD":5000,"RAM":2000,"Printer":6000,"Pendrive":800}
class cashpayment(Bill):
    def __init__(self,total):
        print("Method Payment is cash")
        print("Total amount to pay :",total)
        n20=int(total/2000)
        total=total%2000
        n5=int(total/500)
        total=total%500
        n2=int(total/200)
        total=total%200
        n1=int(total/100)
        total=total%100
        print("")
        print("2000 Rs Notes::",n20)
        print("500 Rs Notes::",n5)
        print("200 Rs Notes::",n2)
        print("100 Rs Notes::",n1)
class chequepayment(Bill):
    def __init__(self,total):
        print("Method Payment is cheque")
        print("Total amount to pay :",total)
        print("enter cheque number:")
        chno=input("enter here")
        print("enter bank  name:")
        bkno=input("enter here")
        print("cheque number:",chno)
        print("bank name:",bkno)
s=Bill()
total=0
for i in  s.item.keys():
    print(i,s.item[i])
    print("-----------")
    print("Want this item ?  (Y/N)",end="")
    ans=input("")
    if(ans.lower()=="y"):
        print("enter no of ",i)
        qu=int(input(""))
        total=total+qu*(int(s.item[i]))
print("1. Cash Payment")
print("2. Cheque Payment")
n=int(input("enter here"))
if(n==1):
    cash=cashpayment(total)
elif n==2:
    chk=chequepayment(total)
else:
    raise Exception("enter from 1 or 2")

HDD 5000
-----------
Want this item ?  (Y/N)y
enter no of  HDD
1
RAM 2000
-----------
Want this item ?  (Y/N)y
enter no of  RAM
1
Printer 6000
-----------
Want this item ?  (Y/N)y
enter no of  Printer
1
Pendrive 800
-----------
Want this item ?  (Y/N)y
enter no of  Pendrive
1
1. Cash Payment
2. Cheque Payment
enter here1
Method Payment is cash
Total amount to pay : 13800

2000 Rs Notes:: 6
500 Rs Notes:: 3
200 Rs Notes:: 1
100 Rs Notes:: 1


## Numpy

In [2]:
import numpy as np
import sys
s=range(1000)
print("size of each element of lis in bytes:",sys.getsizeof(s))
print("size of whole list in bytes:",sys.getsizeof(s)*len(s))


size of each element of lis in bytes: 48
size of whole list in bytes: 48000


In [3]:
d=np.arange(1000)
print("Size of each elemnt of numpy array in bytes",d.itemsize)
print("size of whole numpy array in bytes:",d.itemsize*d.size)

Size of each elemnt of numpy array in bytes 4
size of whole numpy array in bytes: 4000


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [7]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[:1,:3])

[[1 2 3]]


In [8]:
print(arr[:1])

[[1 2 3 4 5]]


In [9]:
arr.shape

(2, 5)

In [10]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=3)
print(arr)

[[[1 2 3 4 5]]]


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(-1,3
                  )
print(newarr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [10]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for j in x:
        print(j)

1
2
3
4
5
6


In [12]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [15]:
for x in np.nditer(arr[0:1,::2]):
    print(x)

1
3


In [17]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [25]:
arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6]])
arr3=np.array([[7,8,9]])
arr=np.concatenate((arr1,arr2,arr3),axis=1)
print(arr)

[[1 2 3 4 5 6 7 8 9]]


In [27]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.array_split(arr1,2)
print(arr)

[array([1, 2]), array([3])]


In [28]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.array_split(arr1,3)
print(arr)

[array([1]), array([2]), array([3])]


In [30]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.array_split(arr1,5)
print(arr)

[array([1]), array([2]), array([3]), array([], dtype=int32), array([], dtype=int32)]


In [37]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
arr2=np.array([4,5,6])
arr=np.array_split(arr1,4,axis=1)
print(arr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [38]:
arr=np.array([1,2,3,9,4,4,7,5,6])
x=np.where(arr==4)
print(x)

(array([4, 5], dtype=int64),)


In [39]:
y=np.where(arr%2==0)
print(y)

(array([1, 4, 5, 8], dtype=int64),)


In [40]:
arr1=np.array([1,2,3,65,45,4,236,6])
 
print(np.sort(arr1))

[  1   2   3   4   6  45  65 236]


In [44]:
arr=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr,axis=1))

[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [50]:
arr=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr,axis=1))

[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]


In [62]:
from numpy import random 
x=random.randint(100)
print(x)

51


In [63]:
from numpy import random 
x=random.randint(100,size=(3,5))
print(x)

[[53 49 79 84 24]
 [87 21 15 62 28]
 [25 48  7 85  1]]


In [67]:
x=random.rand(9)
print(x)

[0.95144932 0.13666494 0.20420579 0.48241034 0.28604546 0.81240693
 0.10601276 0.82090378 0.4481454 ]


In [86]:
x=random.choice([1,3,5,43,3,5],size=(5))
print(x)

[ 5  3  5 43  5]


In [6]:
from numpy import random
x=random.randint(100)
#print(x)
flag=False
for i in range(7):
    print("try no:",(7-i))
    guess=int(input("enter a guesss :"))
    if guess==x:
        print("you guessed the number")
        flag=True
        break
    if guess>x:
        print("--number is lower than input--")
    if guess<x:
        print("--number is higher than input--")
if flag==False:
    print("the number was ",x)

try no: 7
enter a guesss :34
you guessed the number
